//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS_WebApp.Areas.ad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GalleryItem
    {
        public int Id { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> GalleryId { get; set; }
    
        public virtual Gallery Gallery { get; set; }
    }
}
