//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS_WebApp.Areas.ad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeConfig
    {
        public int Id { get; set; }
        public string ViewName { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Items { get; set; }
        public string Alias { get; set; }
    }
}
