//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS_WebApp.Areas.ad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Excerpt { get; set; }
        public string Content { get; set; }
        public Nullable<bool> Enable { get; set; }
        public string ThumnailImagePath { get; set; }
        public int CategoryId { get; set; }
        public string AuthorId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Attachment { get; set; }
        public string MetaTitle { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
