//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS_WebApp.Areas.ad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreReview
    {
        public int Id { get; set; }
        public string StudentId { get; set; }
        public string Fullname { get; set; }
        public string ClassId { get; set; }
        public string StudentDept { get; set; }
        public string CourseId { get; set; }
        public string CourseName { get; set; }
        public string ReviewDept { get; set; }
        public Nullable<double> InitialScore { get; set; }
        public Nullable<double> RevisedScore { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> ProfileId { get; set; }
    
        public virtual ScoreReviewProfile ScoreReviewProfile { get; set; }
    }
}
